In [4]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
df = pd.read_csv("Reviews.csv", nrows=50000)

print(df.head())
print("Rows loaded:", len(df))

   Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1 

In [6]:
sentences = [

    "This olive oil is wonderful and very light on the stomach.",

    "The packaging was broken and let too much light inside the box.",

    "I prefer this brand because it is a light and healthy snack."

]

In [7]:
vectorizer = CountVectorizer()

In [8]:
dtm = vectorizer.fit_transform(sentences)

In [9]:
matrix = dtm.toarray()

print(matrix)

[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]


In [10]:
vec_1 = matrix[0]
vec_2 = matrix[1]
vec_3 = matrix[2]

print("Sentence 1 Vector:")
print(vec_1)

print("\nSentence 2 Vector:")
print(vec_2)

print("\nSentence 3 Vector:")
print(vec_3)

Sentence 1 Vector:
[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]

Sentence 2 Vector:
[1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]

Sentence 3 Vector:
[1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [11]:
similarity_1_2 = np.dot(vec_1, vec_2)

In [12]:
similarity_1_3 = np.dot(vec_1, vec_3)

In [13]:
print("Similarity between Sentence 1 and Sentence 2:")
print(similarity_1_2)

print("\nSimilarity between Sentence 1 and Sentence 3:")
print(similarity_1_3)

Similarity between Sentence 1 and Sentence 2:
4

Similarity between Sentence 1 and Sentence 3:
4
